### ISSUE TITLE
Delay before considering Offline(suggestion/question)

### ISSUE THREAD

**Issue by jasan-s** [RobPando/redux-offline-queue#23]
Not sure how reliable `NetInfo` status is in real-world situations. Would it be better to implement a delay before the device is considered offline?

**Comment by RobPando** [comment]
I actually think is quite reliable. However, considering for a moment that it might not be all that reliable, the library optimistically moves forward with the reducer, so I think it would still be good even if it consider it offline when it was not because once the connectivity is regain the action will be sure to dispatch along with the request, it is just a matter of handling all scenarios correctly. On the other hand delaying the offline action might actually cause problems, for example, if we delay the offline action and redux-offline-queue receives the action **after** the request has been made, it won't queue it. Of course I am super open to hearing if you got any ideas, I am always open to ideas.
